### ISSUE TITLE
HomeWidget.registerBackgroundCallback() throwing error

### ISSUE THREAD

**Issue by VasuGajjar** [ABausG/home_widget#105]
HomeWidget.registerBackgroundCallback() is not working

My Code: 
```
void registerHomeWidgetCallback() async {
    Logger.debug('Registering HomeWidget callback');
    var res = await HomeWidget.registerBackgroundCallback(homeWidgetBackgroundCallback);
    Logger.data('HomeWidget callback status: $res');
  }

dynamic homeWidgetBackgroundCallback(Uri? uri) {}
```

Error: 
```
[log] Registering HomeWidget callback

E/MethodChannel#home_widget(13331): Failed to handle method call

E/MethodChannel#home_widget(13331): java.lang.NullPointerException: null cannot be cast to non-null type kotlin.Number

E/MethodChannel#home_widget(13331): 	at es.antonborri.home_widget.HomeWidgetPlugin.onMethodCall(HomeWidgetPlugin.kt:106)

E/MethodChannel#home_widget(13331): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)

E/MethodChannel#home_widget(13331): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)

E/MethodChannel#home_widget(13331): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)

E/MethodChannel#home_widget(13331): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)

E/MethodChannel#home_widget(13331): 	at android.os.Handler.handleCallback(Handler.java:942)

E/MethodChannel#home_widget(13331): 	at android.os.Handler.dispatchMessage(Handler.java:99)

E/MethodChannel#home_widget(13331): 	at android.os.Looper.loopOnce(Looper.java:201)

E/MethodChannel#home_widget(13331): 	at android.os.Looper.loop(Looper.java:288)

E/MethodChannel#home_widget(13331): 	at android.app.ActivityThread.main(ActivityThread.java:7902)

E/MethodChannel#home_widget(13331): 	at java.lang.reflect.Method.invoke(Native Method)

E/MethodChannel#home_widget(13331): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:553)

E/MethodChannel#home_widget(13331): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

I/ExoPlayerImpl(13331): Init 45cd16b [ExoPlayerLib/2.17.1] [bhima, ZTE A2020G Pro, Xiaomi, 33]

E/flutter (13331): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, null cannot be cast to non-null type kotlin.Number, null, java.lang.NullPointerException: null cannot be cast to non-null type kotlin.Number

E/flutter (13331): 	at es.antonborri.home_widget.HomeWidgetPlugin.onMethodCall(HomeWidgetPlugin.kt:106)

E/flutter (13331): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)

E/flutter (13331): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)

E/flutter (13331): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)

E/flutter (13331): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)

E/flutter (13331): 	at android.os.Handler.handleCallback(Handler.java:942)

E/flutter (13331): 	at android.os.Handler.dispatchMessage(Handler.java:99)

E/flutter (13331): 	at android.os.Looper.loopOnce(Looper.java:201)

E/flutter (13331): 	at android.os.Looper.loop(Looper.java:288)

E/flutter (13331): 	at android.app.ActivityThread.main(ActivityThread.java:7902)

E/flutter (13331): 	at java.lang.reflect.Method.invoke(Native Method)

E/flutter (13331): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:553)

E/flutter (13331): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

E/flutter (13331): )

E/flutter (13331): #0      StandardMethodCodec.decodeEnvelope package:flutter/…/services/message_codecs.dart:653
E/flutter (13331): #1      MethodChannel._invokeMethod package:flutter/…/services/platform_channel.dart:296

E/flutter (13331): <asynchronous suspension>

E/flutter (13331): #2      PlayerBloc.registerHomeWidgetCallback
package:music_player/…/player/player_bloc.dart:167

E/flutter (13331): <asynchronous suspension>
```

**Comment by khjde1207** [comment]
https://github.com/ABausG/home_widget/issues/96

**Comment by VasuGajjar** [comment]
> #96

The given solution in mentioned issue is not working in my case, I tried it and still getting same error

**Comment by okandemirofficial** [comment]
Still the same error, any fix & workaround?

**Comment by u2tall** [comment]
Same issue here, still unresolved

**Comment by ABausG** [comment]
Few questions:

- What Version if the Package are you using?
- Can you make sure that the callback function itself is declared outside of the class?
- You should also add `@pragma("vm:entry-point")` to the function


Can you try this and comment again? Thank you!

**Comment by u2tall** [comment]
Thanks for your quick response. 
I was using the right package, and had `@pragma("vm:entry-point")`, but I had declared the callback inside the class instead of outside.
Now it's working!
Thanks so much for creating this package and for your help!!
