### ISSUE TITLE
Issue with Android Widget: No Widget found with Name HomeWidgetExampleProvider

### ISSUE THREAD

**Issue by AjayShanker-geek** [ABausG/home_widget#15]
Hi, I am new to flutter. I am having an issue with configuring on Android.

`PlatformException (PlatformException(-3, No Widget found with Name HomeWidgetExampleProvider. Argument 'name' must be the same as your AppWidgetProvider you wish to update, java.lang.ClassNotFoundException: com.ajay.owadio.HomeWidgetExampleProvider
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at java.lang.Class.forName(Class.java:379)
	at es.antonborri.home_widget.HomeWidgetPlugin.onMethodCall(HomeWidgetPlugin.kt:64)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.ajay.owadio.HomeWidgetExampleProvider" on path: DexPathList[[zip file "/data/app/~~ofh_quxw5tSewumlGyuJXQ==/com.ajay.owadio-mgvxU_hG_RGKA8SOFcf_Gg==/base.apk"],nativeLibraryDirectories=[/data/app/~~ofh_quxw5tSewumlGyuJXQ==/com.ajay.owadio-mgvxU_hG_RGKA8SOFcf_Gg==/lib/x86, /data/app/~~ofh_quxw5tSewumlGyuJXQ==/com.ajay.owadio-mgvxU_hG_RGKA8SOFcf_Gg==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 14 more
, null))`

I am unable to solve the issue

**Comment by answer0732** [comment]
I have same problem, How did you solve it ? thanks!

**Comment by desmeit** [comment]
How did you solve this issue?
