### ISSUE TITLE
Unable to instantiate receiver

### ISSUE THREAD

**Issue by vadim-rm** [ABausG/home_widget#22]
Hello! I am having problems with the library. I tried to integrate the example from the library into my project, but I got the following problem:
```
E/AndroidRuntime(27577): java.lang.RuntimeException: Unable to instantiate receiver com.vadimrm.clastere.HomeWidgetProvider: java.lang.ClassNotFoundException: Didn't find class "com.vadimrm.clastere.HomeWidgetProvider" on path: DexPathList[[zip file "/data/app/~~88u_Wa5GQ7Svqajbbr4qdw==/com.vadimrm.clastere-0pEzhjkNxr5w8bTWaCZNsg==/base.apk"],nativeLibraryDirectories=[/data/app/~~88u_Wa5GQ7Svqajbbr4qdw==/com.vadimrm.clastere-0pEzhjkNxr5w8bTWaCZNsg==/lib/x86, /data/app/~~88u_Wa5GQ7Svqajbbr4qdw==/com.vadimrm.clastere-0pEzhjkNxr5w8bTWaCZNsg==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
E/AndroidRuntime(27577): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4018)
E/AndroidRuntime(27577): 	at android.app.ActivityThread.access$1400(ActivityThread.java:237)
E/AndroidRuntime(27577): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1924)
E/AndroidRuntime(27577): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(27577): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(27577): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(27577): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27577): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(27577): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(27577): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.vadimrm.clastere.HomeWidgetProvider" on path: DexPathList[[zip file "/data/app/~~88u_Wa5GQ7Svqajbbr4qdw==/com.vadimrm.clastere-0pEzhjkNxr5w8bTWaCZNsg==/base.apk"],nativeLibraryDirectories=[/data/app/~~88u_Wa5GQ7Svqajbbr4qdw==/com.vadimrm.clastere-0pEzhjkNxr5w8bTWaCZNsg==/lib/x86, /data/app/~~88u_Wa5GQ7Svqajbbr4qdw==/com.vadimrm.clastere-0pEzhjkNxr5w8bTWaCZNsg==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
E/AndroidRuntime(27577): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
E/AndroidRuntime(27577): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(27577): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(27577): 	at android.app.AppComponentFactory.instantiateReceiver(AppComponentFactory.java:110)
E/AndroidRuntime(27577): 	at androidx.core.app.CoreComponentFactory.instantiateReceiver(CoreComponentFactory.java:60)
E/AndroidRuntime(27577): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4011)
E/AndroidRuntime(27577): 	... 8 more
I/Process (27577): Sending signal. PID: 27577 SIG: 9
```
android/build.gradle
```gradle
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath 'com.google.gms:google-services:4.3.5'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
app/build.gradle
```gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}
android {
    compileSdkVersion 29

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "com.vadimrm.clastere"
        minSdkVersion 23
        targetSdkVersion 29
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }
    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
    buildTypes {
        release {
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}
```
project structure:
![image](https://user-images.githubusercontent.com/37626101/116678961-c5fbc980-a9cb-11eb-8c74-4d210e0fb09b.png)
Android manifest:
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.vadimrm.clastere">
    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-sdk
        android:minSdkVersion="8" />
    <application
        android:label="Clastere"
        android:icon="@mipmap/ic_launcher"
        android:networkSecurityConfig="@xml/network_security_config">
        <provider
            android:name="sk.fourq.otaupdate.OtaUpdateFileProvider"
            android:authorities="${applicationId}.ota_update_provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/filepaths" />
        </provider>
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="secret"/>
        <meta-data
            android:name="com.google.android.gms.ads.AD_MANAGER_APP"
            android:value="true"/>
        <activity
            android:name=".MainActivity"
            android:screenOrientation="portrait"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <!-- Displays an Android View that continues showing the launch screen
                 Drawable until Flutter paints its first frame, then this splash
                 screen fades out. A splash screen is useful to avoid any visual
                 gap between the end of Android's launch screen and the painting of
                 Flutter's first frame. -->
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

        <receiver android:name="HomeWidgetProvider" >
            <intent-filter>
                <action android:name="android.appwidget.action.APPWIDGET_UPDATE" />
            </intent-filter>
            <meta-data android:name="android.appwidget.provider"
                android:resource="@xml/widget" />
        </receiver>

        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```
HomeWidgetProvider.kt
```kotlin
package com.vadimrm.clastere

import android.appwidget.AppWidgetManager
import android.content.Context
import android.content.SharedPreferences
import android.net.Uri
import android.widget.RemoteViews
import es.antonborri.home_widget.HomeWidgetBackgroundIntent
import es.antonborri.home_widget.HomeWidgetLaunchIntent
import es.antonborri.home_widget.HomeWidgetProvider

class HomeWidgetExampleProvider : HomeWidgetProvider() {

    override fun onUpdate(context: Context, appWidgetManager: AppWidgetManager, appWidgetIds: IntArray, widgetData: SharedPreferences) {
        appWidgetIds.forEach { widgetId ->
            val views = RemoteViews(context.packageName, R.layout.widget).apply {
                // Open App on Widget Click
                val pendingIntent = HomeWidgetLaunchIntent.getActivity(
                        context,
                        MainActivity::class.java)
                setOnClickPendingIntent(R.id.widget_container, pendingIntent)

                // Swap Title Text by calling Dart Code in the Background
                setTextViewText(R.id.widget_title, widgetData.getString("title", null)
                        ?: "No Title Set")
                val backgroundIntent = HomeWidgetBackgroundIntent.getBroadcast(
                        context,
                        Uri.parse("homeWidgetExample://titleClicked")
                )
                setOnClickPendingIntent(R.id.widget_title, backgroundIntent)

                val message = widgetData.getString("message", null)
                setTextViewText(R.id.widget_message, message
                        ?: "No Message Set")
                // Detect App opened via Click inside Flutter
                val pendingIntentWithData = HomeWidgetLaunchIntent.getActivity(
                        context,
                        MainActivity::class.java,
                        Uri.parse("homeWidgetExample://message?message=$message"))
                setOnClickPendingIntent(R.id.widget_message, pendingIntentWithData)
            }

            appWidgetManager.updateAppWidget(widgetId, views)
        }
    }
}
```
I am new to android development. I would really appreciate your help

**Comment by vadim-rm** [comment]
Android manifest:
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.vadimrm.clastere">
    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-sdk
        android:minSdkVersion="8" />
    <application
        android:label="Clastere"
        android:icon="@mipmap/ic_launcher"
        android:networkSecurityConfig="@xml/network_security_config">
        <provider
            android:name="sk.fourq.otaupdate.OtaUpdateFileProvider"
            android:authorities="${applicationId}.ota_update_provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/filepaths" />
        </provider>
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-6067236207245720~9365373414"/>
<!--        android:value="ca-app-pub-6067236207245720~9365373414"-->
        <meta-data
            android:name="com.google.android.gms.ads.AD_MANAGER_APP"
            android:value="true"/>
        <activity
            android:name=".MainActivity"
            android:screenOrientation="portrait"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <!-- Displays an Android View that continues showing the launch screen
                 Drawable until Flutter paints its first frame, then this splash
                 screen fades out. A splash screen is useful to avoid any visual
                 gap between the end of Android's launch screen and the painting of
                 Flutter's first frame. -->
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

        <receiver android:name="HomeWidgetProvider" >
            <intent-filter>
                <action android:name="android.appwidget.action.APPWIDGET_UPDATE" />
            </intent-filter>
            <meta-data android:name="android.appwidget.provider"
                android:resource="@xml/widget" />
        </receiver>

        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>

```

**Comment by ABausG** [comment]
Could you please edit the issue to also include the code of `HomeWidgetProvider.kt`?

My guess would be that the declared package name in that file does not match your package name declaration in the manifest.

The very first line of `HomeWidgetProvider.kt` should in your case be:
`package com.vadimrm.clastere`

**Comment by vadim-rm** [comment]
> Could you please edit the issue to also include the code of `HomeWidgetProvider.kt`?
Thanks, updated
> The very first line of `HomeWidgetProvider.kt` should in your case be:
> `package com.vadimrm.clastere`
Yes it is

**Comment by ABausG** [comment]
Looking at it again I think you need to change the receiver in your manifest to:

```
<receiver android:name="HomeWidgetExampleProvider" >
    <intent-filter>
        <action android:name="android.appwidget.action.APPWIDGET_UPDATE" />
    </intent-filter>
    <meta-data android:name="android.appwidget.provider"
        android:resource="@xml/home_widget_example" />
</receiver>
```

Key here is the HomeWidget**Example**Provider this should be the name of your concrete implementation

**Comment by vadim-rm** [comment]
I changed this in my manifest and now I get the following error:
```
java.lang.RuntimeException: Unable to instantiate receiver com.vadimrm.clastere.HomeWidgetExampleProvider: java.lang.ClassNotFoundException: Didn't find class "com.vadimrm.clastere.HomeWidgetExampleProvider" on path: DexPathList[[zip file "/data/app/~~Ac8WCJ7smBViISVKOB6AJw==/com.vadimrm.clastere-GxYnqSBMOixeaCg3HRX-hA==/base.apk"],nativeLibraryDirectories=[/data/app/~~Ac8WCJ7smBViISVKOB6AJw==/com.vadimrm.clastere-GxYnqSBMOixeaCg3HRX-hA==/lib/x86, /data/app/~~Ac8WCJ7smBViISVKOB6AJw==/com.vadimrm.clastere-GxYnqSBMOixeaCg3HRX-hA==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
E/AndroidRuntime( 4209): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4018)
E/AndroidRuntime( 4209): 	at android.app.ActivityThread.access$1400(ActivityThread.java:237)
E/AndroidRuntime( 4209): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1924)
E/AndroidRuntime( 4209): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 4209): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 4209): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime( 4209): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4209): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 4209): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime( 4209): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.vadimrm.clastere.HomeWidgetExampleProvider" on path: DexPathList[[zip file "/data/app/~~Ac8WCJ7smBViISVKOB6AJw==/com.vadimrm.clastere-GxYnqSBMOixeaCg3HRX-hA==/base.apk"],nativeLibraryDirectories=[/data/app/~~Ac8WCJ7smBViISVKOB6AJw==/com.vadimrm.clastere-GxYnqSBMOixeaCg3HRX-hA==/lib/x86, /data/app/~~Ac8WCJ7smBViISVKOB6AJw==/com.vadimrm.clastere-GxYnqSBMOixeaCg3HRX-hA==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
E/AndroidRuntime( 4209): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
E/AndroidRuntime( 4209): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime( 4209): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime( 4209): 	at android.app.AppComponentFactory.instantiateReceiver(AppComponentFactory.java:110)
E/AndroidRuntime( 4209): 	at androidx.core.app.CoreComponentFactory.instantiateReceiver(CoreComponentFactory.java:60)
E/AndroidRuntime( 4209): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4011)
E/AndroidRuntime( 4209): 	... 8 more
I/Process ( 4209): Sending signal. PID: 4209 SIG: 9
Lost connection to device
```

**Comment by ABausG** [comment]
This now seems to be a problem of the dex files.
Performing a cleaning of the project and/or reinstalling the app on the device should do the trick I believe

**Comment by vadim-rm** [comment]
I already tried this but it didn't help

**Comment by timorss** [comment]
did u find a solution?

**Comment by vadim-rm** [comment]
> did u find a solution?

Yes, simply do `WidgetsFlutterBinding.ensureInitialized()` in the `void main()` of your app

**Comment by kjawadDeveloper2** [comment]
i am also facing this issue.

**Comment by bbenetskyy** [comment]
> > did u find a solution?
> 
> @timorss Yes, simply do `WidgetsFlutterBinding.ensureInitialized()` in the `void main()` of your app

Unfortunately, I'm still facing that issue even after all that fixes
