### ISSUE TITLE
 HomeWidget.updateWidget not working on Android Release Mode

### ISSUE THREAD

**Issue by th8m0z** [ABausG/home_widget#268]
The widget is not being updated on release mode on Android, debug mode works perfectly.

Logs from Crashlytics show this error:

`PlatformException(-3, No Widget found with Name null. Argument 'name' must be the same as your AppWidgetProvider you wish to update, java.lang.ClassNotFoundException: app.routineflow.routineflow.glance.HomeWidgetReceiver at java.lang.Class.classForName(Native Method) at java.lang.Class.forName(Class.java:536) at java.lang.Class.forName(Class.java:467) at es.antonborri.home_widget.a.onMethodCall(Unknown Source:522) at hh.j$a.a(Unknown Source:17) at wg.c.l(Unknown Source:18) at wg.c.m(Unknown Source:41) at wg.c.i(Unknown Source:0) at wg.b.run(Unknown Source:12) at android.os.Handler.handleCallback(Handler.java:1013) at android.os.Handler.dispatchMessage(Handler.java:101) at android.os.Looper.loopOnce(Looper.java:226) at android.os.Looper.loop(Looper.java:328) at android.app.ActivityThread.main(ActivityThread.java:9190) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) Caused by: java.lang.ClassNotFoundException: app.routineflow.routineflow.glance.HomeWidgetReceiver ... 17 more , null)`

**Comment by ABausG** [comment]
Can you try:
- Use the fully qualified Android Name (using the package import)
- Add your widget receiver class `app.routineflow.routineflow.glance.HomeWidgetReceiver` to the pro guard file so it can find the class even in a shrunk release build

**Comment by MakhmudovBekhruz** [comment]
The same issue, please help asap, it is very urgent now

**Comment by ABausG** [comment]
- Can you additionally provide the way you are calling `HomeWidget.updateWidget`
- Have you tried the steps I mentioned above?

**Comment by MakhmudovBekhruz** [comment]
@ABausG yes I tried those steps but it did not help. Profile and Debug mode are working fine. Problem only in release mode

Flutter version: 3.22.1

**Comment by ABausG** [comment]
Can you paste in your proguard.rules file?

You will then need to whitelist your AppReceiver in order for it to be found when the platform files get obfuscated

**Comment by dario-digregorio** [comment]
I had the same issue and could solve it by adding proguard rules.

add this to your app `build.gradle`
```
 buildTypes {
        release {
            // ...
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
         // ...
    }
```

and create a `proguard-rules.pro` file in the android/app directory. And add this line. Add exceptions for all files related to the widget implementation. In my case they are all inside the widget package/directory.
```
-keepclassmembers class my.flutter.app.widget.** { *; }
```

If you are not sure which rules to add you can upload your apk to this [playground](https://playground.proguard.com/)
